# Generated by Django 3.2.9 on 2021-11-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_precio',
            field=models.FloatField(default=1),
        ),
    ]
